// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjXSWe-rJl8QEVrJMc1welzibrsCX55T0',
    appId: '1:934521875100:web:284e0ce86202c1f8cb9b59',
    messagingSenderId: '934521875100',
    projectId: 'newsapp-c0411',
    authDomain: 'newsapp-c0411.firebaseapp.com',
    storageBucket: 'newsapp-c0411.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZoCLecr7dO8mD2wLHYsWhecm6nmSmMs0',
    appId: '1:934521875100:android:636fd09eee3409b4cb9b59',
    messagingSenderId: '934521875100',
    projectId: 'newsapp-c0411',
    storageBucket: 'newsapp-c0411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfSpuZv8by-HSBk7IYDBwqBIrDB6M1ISw',
    appId: '1:934521875100:ios:e3fde2bf2a475873cb9b59',
    messagingSenderId: '934521875100',
    projectId: 'newsapp-c0411',
    storageBucket: 'newsapp-c0411.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfSpuZv8by-HSBk7IYDBwqBIrDB6M1ISw',
    appId: '1:934521875100:ios:e3fde2bf2a475873cb9b59',
    messagingSenderId: '934521875100',
    projectId: 'newsapp-c0411',
    storageBucket: 'newsapp-c0411.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjXSWe-rJl8QEVrJMc1welzibrsCX55T0',
    appId: '1:934521875100:web:552c89ceca29d1c9cb9b59',
    messagingSenderId: '934521875100',
    projectId: 'newsapp-c0411',
    authDomain: 'newsapp-c0411.firebaseapp.com',
    storageBucket: 'newsapp-c0411.appspot.com',
  );
}
