name: Flutter Integration Test

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

jobs:
  android_tests:
    name: Android Integration Tests
    runs-on: macos-latest  # Using latest macOS runner, which may be ARM-based
    strategy:
      matrix:
        api-level:
          - 29
      fail-fast: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install Flutter dependencies
      run: |
        cd news_app
        flutter pub get

    - name: Run Android Emulator and Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: arm64-v8a  # Use ARM architecture for Apple Silicon compatibility
        profile: Nexus 6
        script: |
          adb wait-for-device shell getprop sys.boot_completed 1>/dev/null;  # Ensure emulator is fully booted
          cd news_app
          flutter drive --target=test_driver/app_test.dart --android-emulator

  ios_tests:
    name: iOS Integration Tests
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install Flutter dependencies
      run: |
        cd news_app
        flutter pub get

    - name: Install CocoaPods
      run: |
        cd news_app/ios
        sudo gem install cocoapods
        pod install

    - name: Build iOS app
      run: |
        cd news_app
        flutter build ios --debug --no-codesign

    - name: Run iOS Simulator and Tests
      run: |
        cd news_app
        flutter emulators --launch apple_ios_simulator
        flutter drive --target=test_driver/app_test.dart
