name: Flutter Integration Test

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

jobs:
  android:
    name: Android Integration Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: List files in news_app
      working-directory: news_app
      run: ls -R

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'

    - name: Install dependencies
      working-directory: news_app
      run: flutter pub get

    - name: Build Android app
      working-directory: news_app
      run: flutter build apk --debug

    - name: Run Android Integration Tests
      working-directory: news_app
      run: flutter drive --target=integration_test/app_test.dart --android-emulator

  ios:
    name: iOS Integration Tests
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: List files in news_app
      working-directory: news_app
      run: ls -R

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'

    - name: Install dependencies
      working-directory: news_app
      run: flutter pub get

    - name: Install CocoaPods
      working-directory: news_app/ios
      run: |
        sudo gem install cocoapods
        pod install

    - name: Build iOS app
      working-directory: news_app
      run: flutter build ios --debug --no-codesign

    - name: Run iOS Integration Tests
      working-directory: news_app
      run: flutter drive --target=integration_test/app_test.dart --ios
