name: Flutter Integration Test

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

jobs:
  android:
    runs-on: macos-11
    strategy:
      matrix:
        api-level:
          - 29  # Specify the API level(s) you want to test on
      fail-fast: true

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install Flutter dependencies
      run: flutter pub get

    - name: Run Android Emulator and Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86_64
        profile: Nexus 6
        script: flutter drive --target=test_driver/app_test.dart --android-emulator

  ios:
    name: iOS Integration Tests
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Install CocoaPods
      run: |
        cd ios
        sudo gem install cocoapods
        pod install

    - name: Build iOS app
      run: flutter build ios --debug --no-codesign

    - name: Run iOS Integration Tests
      run: flutter drive --target=test_driver/app_test.dart --ios
